services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=markets'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "${PG_HOST_PORT:-5433}:5432" # Expose on different host port to avoid conflict with local Postgres